blank_issues_enabled: false
contact_links:
  - name: Want to suggest a new feature or report a bug?
    url: https://github.com/hixbe/hixbe
    about: This repository is only for font file submissions only.
