name: Build Bangla Fonts [Force Rebuild No Deploy] [Manual]

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure Git for large repositories
        run: |
          git config diff.renameLimit 999999
          git config merge.renameLimit 999999
          git config core.preloadindex true
          git config core.fscache true
          git config gc.auto 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Playwright Setup
        run: bunx playwright install --with-deps chromium

      - name: Generate fontlist
        run: bun run fontlist

      - name: Save Hixbe metadata
        run: bun run metadata

      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_message: "chore(build): update packages [Manual] [Force]"
        continue-on-error: true




