name: Build and Release Bangla Fonts [Manual]

on:
  push:
    branches: [main]
    paths:
      - 'fonts/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure Git for large repositories
        run: |
          git config diff.renameLimit 999999
          git config merge.renameLimit 999999
          git config core.preloadindex true
          git config core.fscache true
          git config gc.auto 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Playwright Setup
        run: bunx playwright install --with-deps chromium

      - name: Remove Duplicates
        run: bun run check-duplicates

      - name: Generate fontlist
        run: bun run fontlist

      - name: Save Hixbe metadata
        run: bun run metadata

      - name: Setup Git Config
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Publish to NPM
        run: npx @hixbe/font-publisher publish patch --yes --provenance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}




